### ISSUE TITLE
No results or stored data after 30 min. 

### ISSUE THREAD

**Issue by techyogi** [Vincent-liuwingsang/unlost#3]
Clean install on m3 max running latest macOS (not beta) and as best I can tell nothing stored or working.

**Comment by Vincent-liuwingsang** [comment]
Are you using the latest version or building locally?

**Comment by Vincent-liuwingsang** [comment]
I;ve recompiled the app and updated the link to correct app. 
Can you try again?
https://github.com/Vincent-liuwingsang/unlost/releases/download/main/unlost.dmg

**Comment by techyogi** [comment]
trying. Thanks.

**Comment by Stooovie** [comment]
same, no results whatsoever after 15 hours. Privileges are granted.

**Comment by techyogi** [comment]
Thought this worked but shows no screenshot since March 7...
